# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

############################## PRE ##############################
  before_all do

    update_fastlane
        ensure_git_status_clean
        git_pull
    carthage(

      command: "bootstrap",

      platform: "iOS",

      use_binaries: false

  )


  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :codeSigning do
    match(app_identifier:["mei.mozilla.ios.Fennec"])
  end

  lane :ci do
    run_tests
  end

  lane :development do
    register_devices(devices_file: "fastlane/devices.txt")
    match(type: "development", force_for_new_devices: false)
  end


  lane :adhoc do
    register_devices(devices_file: "fastlane/devices.txt")
    match(git_url: "git@github.com:SaySayK/MeiFastlaneMatch.git",
      type: "adhoc",
      app_identifier: "mei.mozilla.ios.Fennec")
      gym(scheme: "Fennec",
        output_name: "FirefoxAdhoc.ipa",
                  configuration: "FirefoxBetaDev",
                  export_method: 'ad-hoc',
        silent: false,
        output_directory: "./build"
      )
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  lane :dev_beta do
    match(git_url: "git@github.com:SaySayK/MeiFastlaneMatch.git",
        type: "appstore",
        app_identifier: "mei.mozilla.ios.Fennec"
    )
    produce(
        username: "meiyucrider@gmail.com",
        app_identifier: 'mei.mozilla.ios.Fennec',
        app_name: 'Firefox Test',
        language: 'English',
        app_version: '1.0.1',
        team_name: 'Yong Yu' # only necessary when in multiple teams
    )

    gym(
        project: "Client.xcodeproj",
        scheme: "Fennec",
        configuration: "FirefoxBetaDev",
        export_method: "app-store",
        output_directory: "./build",
        output_name: "FirefoxBeta"
    )
  end

  lane :staging_beta do
    match(git_url: "git@github.com:SaySayK/MeiFastlaneMatch.git",
        type: "appstore",
        app_identifier: "mei.mozilla.ios.Fennec"
    )
    produce(
        username: "meiyucrider@gmail.com",
        app_identifier: 'mei.mozilla.ios.Fennec',
        app_name: 'Firefox Test',
        language: 'English',
        app_version: '1.0.1',
        team_name: 'Yong Yu' # only necessary when in multiple teams
    )

    gym(
        project: "Client.xcodeproj",
        scheme: "Fennec",
        configuration: "FirefoxBetaStaging",
        export_method: "app-store",
        output_directory: "./build",
        output_name: "FirefoxBeta"
    )
  end


  #### This one is being worked on to add TestFlight stuff
  lane :release do
    match(git_url: "git@github.com:SaySayK/MeiFastlaneMatch.git",
        type: "appstore",
        app_identifier: "mei.mozilla.ios.Fennec"
    )
    produce(
        username: "meiyucrider@gmail.com",
        app_identifier: 'mei.mozilla.ios.Fennec',
        app_name: 'Firefox Test',
        language: 'English',
        app_version: '1.0.1',
        team_name: 'Yong Yu' # only necessary when in multiple teams
    )

    gym(
        project: "Client.xcodeproj",
        scheme: "Fennec",
        configuration: "FirefoxBeta",
        export_method: "app-store",
        output_directory: "./build",
        output_name: "FirefoxRelease"
    )

    testflight(
        username: "meiyucrider@gmail.com",
        app_identifier: "mei.mozilla.ios.Fennec",
        beta_app_description: "This is a new build and should be dynamic, from prompt",
        beta_app_feedback_email: "meiyu@saysayk.com",
        itc_provider: "584914"
        # pass a specific value to the iTMSTransporter -itc_provider                   option
      )

  end

end
